# Site settings
title: NolzenLab Blog
SEOTitle: 놀젠스튜디오 연구소 블로그 | NolzenLab Blog
header-img: img/home-bg.jpg
email: nolzenlab@gmail.com
description: "이곳은 @놀젠스튜디오 연구소 블로그입니다. 여러분과 함께 더 큰 세상을 탐험하세요 | 멋진 프로그래머가 되어보세요"
keyword: "nolzenlab, nolzenstudio, NolzenLab Blog, unity, unreal, c, c++, c#, AI, MCP"
url: "https://nolzenlab.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username: huxpro
#zhihu_username: huxpro
github_username: nolzenlab
#twitter_username: huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.ko.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: KR

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: #hux

# Netease settings
netease_comment: false

# Utteranc settings #(https://velog.io/@outstandingboy/Github-%EB%B8%94%EB%A1%9C%EA%B7%B8%EC%97%90-%EB%8C%93%EA%B8%80-%EA%B8%B0%EB%8A%A5-%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0-ft.-Utterances)
utteranc_comment: true

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "" #"UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: #huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "놀젠스튜디오 연구원 <br> 개발 연구 @nolzenstudio"
sidebar-avatar: https://nolzenlab.github.io/img/my_img.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "NolzenStudio", href: "http://nolzenstudio.github.io/" },
    { title: "MAMEdev", href: "https://github.com/mamedev/" },
    { title: "EmulatorJS", href: "https://github.com/EmulatorJS/" },
    { title: "cozrouki", href: "https://github.com/cozrouki/" },
    { title: "LGWebOS", href: "https://webostv.developer.lge.com/" },
    { title: "ouki007", href: "https://github.com/ouki007/" },
  ]
